/*
** EPITECH PROJECT, 2021
** 42sh
** File description:
** list_built_ins
*/

#ifndef BUILTINSLIST_H_
#define BUILTINSLIST_H_

static char builtins[68][10] =
{
    {":"},
    {"@"},
    {"alias"},
    {"echo"},
    {"bg"},
    {"bindkey"},
    {"break"},
    {"breaksw"},
    {"builtins"},
    {"case"},
    {"cd"},
    {"chdir"},
    {"complete"},
    {"continue"},
    {"default"},
    {"dirs"},
    {"echo"},
    {"echotc"},
    {"else"},
    {"end"},
    {"endif"},
    {"endsw"},
    {"eval"},
    {"exec"},
    {"exit"},
    {"fg"},
    {"filetest"},
    {"foreach"},
    {"glob"},
    {"goto"},
    {"hashstat"},
    {"history"},
    {"hup"},
    {"if"},
    {"jobs"},
    {"kill"},
    {"limit"},
    {"log"},
    {"login"},
    {"logout"},
    {"ls-F"},
    {"nice"},
    {"nohup"},
    {"notify"},
    {"onintr"},
    {"popd"},
    {"printenv"},
    {"pushd"},
    {"rehash"},
    {"repeat"},
    {"sched"},
    {"set"},
    {"setenv"},
    {"settc"},
    {"setty"},
    {"shift"},
    {"source"},
    {"stop"},
    {"suspend"},
    {"switch"},
    {"telltc"},
    {"termname"},
    {"time"},
    {"umask"},
    {"unalias"},
    {"uncomplete"},
    {"unhash"},
    {"unlimit"},
};

#endif